### PR TITLE
Fix subsequent lot click bug; additional cleanup;

### LINKED ISSUE #882: Can't load lot profiles
On staging, after successfully clicking on one lot, I can't click on a neighboring lot and get the profile to load.

Steps to reproduce:
- Load https://zola-staging.planninglabs.nyc/l/lot/1/1225/29
- Try clicking on a nearby lot like 39
- See that the URL updates to https://zola-staging.planninglabs.nyc/l/lot/1/1225/39, but the profile provides an error message "Oops. Something went wrong... Please check the address and try again."

@allthesignals Is this the new message for Carto timeouts?

### PR DESCRIPTION
**Pull request by allthesignals**
Closes #882 by implementing a better strategy for triggering updates to the data loader task.

Includes some additional cleanup of unnecessary dependencies.

### CODE REVIEW

File: app/app.js [hunk 1]
```diff
@@ -36,7 +40,4 @@ Ember.MODEL_FACTORY_INJECTIONS = true;
 
 loadInitializers(App, config.modulePrefix);
 
-// TODO: why is this here?
```
Comment (julialucyhogan) [inline app/app.js]: love deleting these yaaaaay!
